# Generated by Django 3.1.1 on 2020-09-21 12:56

from django.db import migrations, models
import userform_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your name', max_length=256)),
                ('email', models.CharField(help_text='Your email address', max_length=256)),
                ('dob', models.DateField(help_text='Your date of birth')),
                ('phone', models.BigIntegerField(help_text='Your phone', validators=[userform_api.models.validate_phone])),
            ],
        ),
    ]
