# Generated by Django 3.1.1 on 2020-09-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(help_text='Your email address', max_length=256),
        ),
    ]
