# Generated by Django 3.1.1 on 2020-09-22 10:32

from django.db import migrations, models
import userform_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('userform_api', '0002_auto_20200921_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(help_text='Your phone', max_length=12, validators=[userform_api.models.validate_phone]),
        ),
    ]
