version: '3'

services:


  # The API application running on gunicorn
  web:
    restart: always
    image: web
    build: ./
    command: >
      bash -c "./manage.py migrate &&
              ./manage.py collectstatic --noinput &&
              gunicorn --bind 0.0.0.0:8000 --access-logfile - userform.wsgi:application"
    volumes:
      - ./:/code:Z
      - static_volume:/static
    expose:
      - 8000


  # Nginx server exposed to the internet
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/static/
    ports:
      - 80:80
    depends_on:
      - web


volumes: 
  static_volume: